### PR TITLE
Fix new resource upload and some ES6 (fix #744)

### LINKED ISSUE #744: 404 error on new ressource upload
## Detailed Description
On a dataset admin page, when I try to upload a ressource file (Local resource>upload from my computer), I have a 404 error:
screenshot-next data gouv fr 2017-02-07 09-01-46

## Your Environment
Version 1.0.0.dev1295

### PR DESCRIPTION
**Pull request by noirbizarre**
See #744 

Fix undefined dataset on add-modal.vue by using `props` instead of `data`.

Everything else is simply ES6 migration.

### CODE REVIEW

File: js/components/dataset/resource/add-modal.vue [hunk 1]
```diff
@@ -23,19 +23,19 @@
...
-    components: {
-        'modal': require('components/modal.vue'),
-        'resource-form': require('components/dataset/resource/form.vue')
+    props: {
+        dataset: {
+            type: Dataset,
+            required: true,
+        }
     },
+    components: {Modal,ResourceForm},
```
Comment (vinyll) [inline js/components/dataset/resource/add-modal.vue]: missing a space `, ResourceForm`

File: js/components/dataset/resource/file-form.vue [hunk 2]
```diff
@@ -57,10 +57,12 @@
 import API from 'api';
 import Dataset from 'models/dataset';
 import CommunityResource from 'models/communityresource';
+import FormHorizontal from 'components/form/horizontal-form.vue';
```
Comment (vinyll) [inline js/components/dataset/resource/file-form.vue]: I suppose you're trying not to redo the templates but `HorintalForm` would have made more sense.

Comment (noirbizarre) [inline js/components/dataset/resource/file-form.vue]: Yep, trying to make some minimal changes (even with ES6 changes).
I added this case to #753
