### PR TITLE
Datepicker fix #1368

### LINKED ISSUE #1368: Datepicking gone wrong
## Detailed Description

When I create or edit a dataset, I have the following problem with the date picker on the "Temporal coverage" field: for a given year `Y`, the date picker switches from `November Y` to `December Y+1` and from `February Y` to `January Y-1`.

## Context

When create or edit a dataset , I want to be able to select all dates from a given year on the date picker.

## Possible Implementation

Fix it.

## Your Environment

* Browser Name and version: Safari, Chrome evergreen
* Operating System and version (desktop or mobile): Mac OS
* uData : data.gouv.fr `udata 1.2.8`

### PR DESCRIPTION
**Pull request by abulte**
This fixes #1368 but introduces a new problem for now: `currentMonthDays` is not recomputed when `current` changes.

I've been looking at this code for too long now, dropping this here for pairing / help.

I can not explain either why the original solution was not working (regarding the switch from November to December and from February to January).

**Edit: it now works with a hack around change detection.**

### CODE REVIEW

File: js/components/calendar.vue [hunk 1]
```diff
@@ -220,7 +216,7 @@ export default {
         },
 
         isMonthDisabled(idx) {
-            const month = moment().month(idx).year(this.currentYear);
+            const month = moment().month(idx).year(this.current.year());
```
Comment (abulte) [inline js/components/calendar.vue]: this should be `const month = this.current.clone().month(idx)`

**Comment by abulte** [comment]
NB: I find the new code easier to read.

File: js/components/calendar.vue (hunk 1 above)
Comment (noirbizarre) [reply js/components/calendar.vue]: Agreed but non-significant here I think.
