### PR TITLE
Fixing some upload bugs on drag-n-drop zone

### LINKED ISSUE #2483: Error when drag and dropping file for resource
When adding a resource on the drag and drop module in the admin, it fails frequently saying the variable `this.$upload` is undefined.

Sentry's event id is [243e70a18d244742864daee00f243959](https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/660260/events/8373351/)

### PR DESCRIPTION
**Pull request by JulienParis**
fix #2483

in extenso  : 

- fixes the error on the admin drag'n drop zone when clicking on the `add a resource` button from the public view on a dataset (A) ;
- fixes the error on admin drag'n drop zone when clicking on the `update a resource` button from the public view of a dataset (B) ;

----

Capture d’écran 2020-06-25 à 15 57 53

### CODE REVIEW

**Comment by JulienParis** [comment]
seems to get the job done now... I opened this PR for review... I tested locally and on demo, on FF and chrome for now

**Comment by JulienParis** [comment]
to sum up the tests I'm doing today on demo server : 

| checkbox | OS | browser | bugfix test |
| :---:  | :---: | :---: | :---: |
| &check; | macOS | Firefox | `add new resource` |
| &check; | macOS | Firefox | `update resource` |
| &check; | macOS | Chrome | `add new resource` |
| &check; | macOS | Chrome | `update resource` |
| to do | macOS | Safari | `add new resource` |
| to do | macOS | Safari | `update resource` |

File: js/components/dataset/resource/list.vue [hunk 1]
```diff
@@ -135,14 +135,14 @@
...
-import Uploader from 'mixins/uploader';
 import Box from 'components/containers/box.vue';
 import ResourceAvailability from './availability.vue';
+import UploaderMixin from 'mixins/uploader';
 import DatasetFilters from 'components/dataset/filters';
 
 export default {
     name: 'resources-list',
-    mixins: [Uploader, Sorter, DatasetFilters],
+    mixins: [Sorter, UploaderMixin, DatasetFilters],
```
Comment (JulienParis) [inline js/components/dataset/resource/list.vue:145]: renamed it to be iso with other imports

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 - Removed now useless metric fetching [#2482](https://github.com/opendatateam/udata/pull/2484)
 - Fix bug in harvester's cron schedule [#2493](https://github.com/opendatateam/udata/pull/2493)
 - Adding banner options in settings for a potential use in an udata's theme [#2492](https://github.com/opendatateam/udata/pull/2492)
+- Fixing a recurrent bug - see logs in Sentry - when opening the drag'n'drop modal directly from a dataset public view for uploading resources (clicking on the `add a resource` button/block) or when trying to update a resource directly from the dataset's public view (clicking on the `update the resource` button) [#2483](https://github.com/opendatateam/udata/pull/2483)...
```
Comment (abulte) [inline CHANGELOG.md:13]:
```suggestion
- Fix JS error when uploading a resource in certain conditions [#2483](https://github.com/opendatateam/udata/pull/2483)
```

keep it simple and use the description of the PR to give more (clear) details.

File: js/components/dataset/resource/form.vue [hunk 3]
```diff
@@ -264,7 +265,7 @@ export default {
             const route_new = this.resource.id ? '' : 'new_';
             const route_namespace = this.is_community ? 'community_' : 'dataset_';
             const endpoint = `upload_${route_new}${route_namespace}resource`;
-            return operations[endpoint].urlify(params);
+            return operations && operations[endpoint].urlify(params);
```
Comment (abulte) [inline js/components/dataset/resource/form.vue:268]: you're testing for `!operations` above, why do you need it again here?

File: js/mixins/uploader.js [hunk 4]
```diff
@@ -222,7 +222,7 @@ export default {
          * See: http://docs.fineuploader.com/branch/master/features/drag-and-drop.html#processingDroppedFilesComplete
          */
         on_dropped_files_complete(files) {
-            if (this.canDrop) {
+            if (this.canDrop && this.$uploader) {
```
Comment (abulte) [inline js/mixins/uploader.js:225]: what happens if `!this.$uploader`? drop cancels/fails? this might be hard to test though.

File: js/components/dataset/resource/form.vue (hunk 3 above)
Comment (JulienParis) [reply js/components/dataset/resource/form.vue]: u're right, no need for that anymore.... the blocking point was the missing check against `this.isUpload` upper

File: js/mixins/uploader.js (hunk 4 above)
Comment (JulienParis) [reply js/mixins/uploader.js]: on my last commit I got back to the original version, without the check against `this.$uploader` as it was before. 

Seems to work as it was, the other checks and changes I did seem to prevent `$uploader` from _not_ being set at this point now...
