### PR TITLE
Fix image upload from admin and some ES6 (fix #743)

### LINKED ISSUE #743: Error 405 on avatar upload
## Detailed Description
On the user admin (admin/me/), when I try to upload a new avatar, I have the following 405 error:

screenshot-next data gouv fr 2017-02-07 08-55-10

The same happen on organization logo upload.

## Your Environment
Version 1.0.0.dev1295

### PR DESCRIPTION
**Pull request by noirbizarre**
See #743

The fix is to use `props` instead of `data`.

### CODE REVIEW

File: js/components/widgets/image-picker.vue [hunk 1]
```diff
@@ -129,9 +128,9 @@ export default {
         }
     },
     methods: {
-        save: function() {
+        save() {
             if (this.HAS_FILE_API) {
-                let data = {};
+                const data = {};
```
Comment (vinyll) [inline js/components/widgets/image-picker.vue]: I'm only a little puzzle by this as it is declared as a constant though will be treated as a viariable object (`data.bbox =`). I know JS does not throw an error yet but I'd rather keep `let` in this case.

Comment (noirbizarre) [inline js/components/widgets/image-picker.vue]: `const` doesn't mean this a constant but that the variable reference is constant ie. the identifier cannot be reassign.
So in case of `Array` or `Object`, if you affect inner members, you still should use `const` if you don't reaffect the variable itself. It would have been wrong if there were `data = {}` somewhere.

I'm just applying the linter recommandations ;)

Comment (vinyll) [inline js/components/widgets/image-picker.vue]: That's right: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const 

> in case the content is an object, this means the object itself can still be altered

👍

Comment (noirbizarre) [inline js/components/widgets/image-picker.vue]: ;)
