### PR TITLE
fix discussions UI

### LINKED ISSUE #2061: Paginate discussions on frontend
On a dataset page, the discussions are not paginated, i.e. only the first page appears. The pagination mechanism is available on the backend/API.

We should implement this feature on the client side.

### PR DESCRIPTION
**Pull request by taniki**
- [x] glitch when message is short
- [x] missing pagination
- [x] restore deep links
- [x] substitute ad-hoc js code to swagger.js model

FIX #2061 

## UI

image

### CODE REVIEW

**Comment by taniki** [comment]
deeplinks are kind of broken but I have no easy fix right now.

**Comment by taniki** [comment]
https://github.com/opendatateam/udata/issues/2061

File: js/components/discussions/threads.vue [hunk 1]
```diff
@@ -117,26 +132,37 @@
...
+                },
+                mask: MASK
+            }),
             loading: true,
             formDisplayed: false,
             currentUser: config.user,
         }
     },
     props: {
+//        discussions: null,
```
Comment (abulte) [inline js/components/discussions/threads.vue]: Remove

File: js/components/discussions/threads.vue [hunk 2]
```diff
@@ -166,17 +192,7 @@ export default {
...
-            this.loading = false;
-            this.discussions = response.data;
-
-            if (document.location.hash) {
-                this.$nextTick(() => { // Wait for data to be binded
-                    this.jumpToHash(document.location.hash);
-                });
-            }
-        }).catch(log.error.bind(log));
+        this.discussions.fetch({for: this.subjectId});
```
Comment (abulte) [inline js/components/discussions/threads.vue]: I _think_ using this instead of `$api.get` makes us dependent on `swagger.json` on the frontend, which we avoided until now and clearly don't want. Can you check?

Comment (taniki) [reply js/components/discussions/threads.vue]: :skull:

Comment (abulte) [reply js/components/discussions/threads.vue]: 😇

**Comment by taniki** [comment]
cf description. I have given some thoughts about this part of UI and pagination will be better on top.

File: js/components/discussions/threads.vue (hunk 1 above)
Comment (abulte) [reply js/components/discussions/threads.vue]: Up ;-)

**Comment by taniki** [comment]
Removing the "part of organisation" badge. Opening an issue about API and feasibility for later.

File: js/components/discussions/threads.vue [hunk 3]
```diff
@@ -243,19 +256,50 @@ export default {
...
+            this.loading = true;
 
-        form {
-            padding: 1em;
+            this.$api.get('discussions/', {for: this.subjectId, page: page}).then(response => {
+                this.loading = false;
+
+                this.discussions = response.data;
+
+                console.log(response)
```
Comment (abulte) [inline js/components/discussions/threads.vue]: 🗑

File: js/components/discussions/threads.vue [hunk 4]
```diff
@@ -243,19 +256,50 @@ export default {
...
+                        this.go_to_page(response.page + 1);
+                    }
+                }
+
+                const pagination = {
+                    page: response.page,
+                    page_size: response.page_size,
+                    pages: pages,
+                    go_to_page: this.go_to_page,
+                    previousPage: previous,
```
Comment (abulte) [inline js/components/discussions/threads.vue]: maybe `previous_page` (ugly but consistent)

File: js/components/discussions/threads.vue [hunk 5]
```diff
@@ -243,19 +256,50 @@ export default {
...
+                    nextPage: next
```
Comment (abulte) [inline js/components/discussions/threads.vue]: maybe `next_page` (ugly but consistent)
